### ISSUE TITLE
BUG: ValueError: unable to compute stem of... (with solution)

### ISSUE THREAD

**Issue by sthaar** [vocalpy/vak#523] opened 2022-06-22 22:00 UTC
With @yangzheng-121, running `vak prep` using .wav files and .csv annotations, we got the following error: 

`File "... .local/lib/python3.8/site-packages/vak/annotation.py", line 172, in recursive_stem
    raise ValueError(f"unable to compute stem of {path}")
ValueError: unable to compute stem of ...`

The stem was correctly found (checked with `print(stem)'. We think it maybe because annotation.py is written for files with annotation extension _after_ the audio file extension (e.g. cbin.non.mat). Thus, the recursive loop removing extensions is looking for another extension while it was the final one. 

**SOLUTION**
in annotation.py line 169 (before while loop), add the line
`if ext:`
this skips the following loop (that replaces extensions) after the last extension has been removed (in our case .wav)

**To Reproduce**

- audio files with .wav extension (e.g. file1.wav)
- annotation files .csv extention (e.g. file1.csv)
   annotations have three columns: onset_s, label and offset_s
- adjust toml file according to steps in [tutorial] (https://vak.readthedocs.io/en/latest/get_started/autoannotate.html#prepare-training-dataset) to point to the directory with correct files
- run `vak prep DIRNAME`

**Desktop (please complete the following information):**
 - Operating System: [Linux, Windows]
 - Version vak 0.4.2

**Additional context**
another workaround may be using the adjusted praat script (https://github.com/sthaar/praatscripts/blob/main/textgrids_to_csv_fortweetynet.praat) creating .wav.csv extension for annotations files
but I haven't tested it yet and it is a less flexible solution

**Comment by NickleDave** [comment] 2022-06-22 22:05
Hi @sthaar and @yangzheng-121 

This is not a bug although I realize it's not obvious.  
Your annotation files need to follow the naming convention described here:
https://vak.readthedocs.io/en/latest/howto/howto_user_annot.html#method-1-converting-your-annotations-to-the-simple-seq-format

> For vak to be able to find the annotation file and the corresponding file that it annotates, you will need to follow a naming convention: the annotation file should have the same name as the file that it annotates, but with the extension of the annotation format added. So, for example, if you have an audio file named “BB_SGP16-1___20160521_214723.wav”, then the file with its annotations in 'simple-seq' format should be named “BB_SGP16-1___20160521_214723.wav.csv”.
> This is also true for any built-in annotation format where there’s a one-to-one relationship from annotation file to the file it annotates, like Audacity .txt files, or Praat .TextGrid files.

So in your example above, your file should be named: 
file1.wav.csv (not file1.csv)

Can you please re-name your .csv files with the expected naming convention and test whether that fixes the issue?

**Comment by NickleDave** [comment] 2022-06-22 22:11
Please let me know if there's a way we can re-write the docs to make it clearer that users need to follow this convention.

We chose to do it this way so that a "plain" .csv file (without the added extension) could be used for other purposes, e.g. analysis, and still co-exist with annotations in the same directory. Maybe it would help to state that reasoning

**Comment by sthaar** [comment] 2022-06-22 22:58
Ah sorry I missed that convention. I guess I just didn't expect it. The explanation would help, but you'd still need to look for it. Maybe make it more explicit in the tutorial? And/or refer to it in the error message? 

In any case .wav.csv works! So problem solved. Thanks!

**Comment by NickleDave** [comment] 2022-06-22 23:13
> The explanation would help, but you'd still need to look for it. Maybe make it more explicit in the tutorial? And/or refer to it in the error message?

All good ideas, thank you

> In any case .wav.csv works! So problem solved. Thanks!

Excellent! Closing

**Closed by NickleDave** 2022-06-22 23:13 UTC
Labels: BUG
