### ISSUE TITLE
BUG: Getting a warning about missing logger directories

### ISSUE THREAD

**Issue by yardencsGitHub** [vocalpy/vak#709] opened 2023-09-29 14:15 UTC
**Describe the bug**
When running 'vak train' or 'vak predict' from the command line I am getting a warning about a missing logger folder:

> Missing logger folder: C:\Users\snabar\Documents\temp_canary_song_data\train\results\results_230928_105731\TweetyNet\lightning_logs

**To Reproduce**
Run as above

**Desktop (please complete the following information):**
 - Operating System: Windows
 - Version 1.0.0a2

**Comment by NickleDave** [comment] 2023-10-23 21:20
According to this issue, the warning is intended behavior -- it's just saying "there's no lightning_logs directory yet, so I'm going to make one":
https://github.com/Lightning-AI/lightning/discussions/12276

I'm going to close this

**Closed by NickleDave** 2023-10-23 21:20 UTC
Labels: BUG
